variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
    
stages:
  - deploy

kubernetes:
  stage: deploy
  image: argoproj/argocd:v2.3.3
  environment:
    name: k8s_deploy
    url: https://dvorov-ivan-04.k8s.praktikum-services.tech
  script:
    - argocd --grpc-web --auth-token $ARGO_TOKEN --server $ARGO_SERVER app set sausage-store-dvorov-ivan -p backend.image=${BACKEND_IMAGE_URL}
    - argocd --grpc-web --auth-token $ARGO_TOKEN --server $ARGO_SERVER app set sausage-store-dvorov-ivan -p frontend.image=${FRONTEND_IMAGE_URL}
    - argocd --grpc-web --auth-token $ARGO_TOKEN --server $ARGO_SERVER app set sausage-store-dvorov-ivan -p backend-report.image=${BACKEND_REPORT_IMAGE_URL}
    - argocd --grpc-web --auth-token $ARGO_TOKEN --server $ARGO_SERVER app sync sausage-store-dvorov-ivan  