stages:
  - deploy

k8s-deploy:
  stage: deploy
  image: docker:20.10.12-dind
  only:
    changes: #как только происходит изменение в папке kubernetes, запускается дочерний пайплайн, который лежит в этой папке
    - kubernetes/**/*
  script:
    - apk add curl
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - mkdir -p ~/.kube/
    - echo "$K8S_CONFIG" >> ~/.kube/config
    - cd kubernetes
    - kubectl apply -f backend
    - sleep 16
    - kubectl apply -f frontend
    - sleep 10
    - kubectl apply -f backend-reports
    - rm -rf ~/.kube
  environment:
    name: staging
    url: https://dvorov-ivan-04.k8s.praktikum-services.tech