stages:
  - deploy

k8s-deploy:
  stage: deploy
  image: alpine/k8s:1.22.10
  only:
    changes: #как только происходит изменение в папке kubernetes, запускается дочерний пайплайн, который лежит в этой папке
    # - kubernetes/**/*
    - sausage-store-chart/**/*
  script:
    - helm package sausage-store-chart
    - curl -v -u $NEXUS_USER:$NEXUS_PASS $NEXUS_HELM_REPO --upload-file sausage-store-chart-1.0.8.tgz
    - helm repo add nexus $NEXUS_HELM_REPO --username $NEXUS_USER --password $NEXUS_PASS
    - helm repo update
    - mkdir -p ~/.kube/
    - echo "$K8S_CONFIG" >> ~/.kube/config
    - |
      helm upgrade --install sausage-store \
      --set environment=test \
      --set fqdn=dvorov-ivan-04.k8s.praktikum-services.tech \
      --atomic --timeout 1m \
      nexus/sausage-store-chart
    - rm -rf ~/.kube
  environment:
    name: staging
    url: https://dvorov-ivan-04.k8s.praktikum-services.tech